print
(" wow, I love the smell of",
       input ("holaday"),
       ". I get to play",
       input ("video game"),
       "on my",
       input ("electronic or concle"),
       ". my mom hates when i play it but my dad is very",
       input ("feeling"),
       "so he dosen't care at all. yesterday my sister took an",
       input ("sharp object"),
       "to my",
       input ("electronic or concle"),
       ". i punched her untill she bacicly",
       input ("way to get around"),
       "to",
       input ("a place"),
       ".i was satisfied now on my",
       input ("electronic or concle"),
       ".holowene was",
       input ("great awesome bad horid something like that"),
       ".")

