import turtle

turtle.left(90)
turtle.forward(90)
turtle.left(90)
turtle.forward(75)
turtle.up()
turtle.goto(0,0)
turtle.down()
turtle.right(90)
turtle.right(90)
turtle.forward(90)
turtle.right(90)
turtle.forward(75)
turtle.up()
turtle.goto(0,0)

turtle.left(90)
turtle.forward(90)
turtle.left(90)
turtle.forward(75)
turtle.up()
turtle.goto(0,0)
turtle.down()
turtle.right(90)
turtle.right(90)
turtle.forward(90)
turtle.right(90)
turtle.forward(75)
